name: devnology
description: app for Devnology
version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  flutter_mobx: 2.0.5
  mobx: 2.0.7
  flutter_modular: 4.5.1+1
  hive: 2.1.0
  hive_flutter: 1.1.0
  intl: any
  carousel_slider: ^4.1.1
  share_plus: ^4.0.4

dev_dependencies:
  mockito: 5.0.15
  modular_codegen: 3.0.2
  mobx_codegen: 2.0.2
  build_runner: 2.1.10
  hive_generator: 1.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/images/logo.png
      - assets/images/apparel.png
      - assets/images/beauty.png
      - assets/images/shoes.png
      - assets/images/seeall.png
      - assets/images/latest1.png
      - assets/images/latest2.png
      - assets/images/product1.png
      - assets/images/product2.png
      - assets/images/product3.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
