// Mocks generated by Mockito 5.0.15 from annotations
// in devnology/test/core/infra/repositories/product_repository_hive_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:devnology/core/infra/adapters/local_storage_adapter_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ILocalStorageAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocalStorageAdapter extends _i1.Mock
    implements _i2.ILocalStorageAdapter {
  MockILocalStorageAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> connect() =>
      (super.noSuchMethod(Invocation.method(#connect, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<dynamic> get(String? collectionName, String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [collectionName, key]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> getAll(String? collectionName) =>
      (super.noSuchMethod(Invocation.method(#getAll, [collectionName]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(String? collectionName, String? key, dynamic value) =>
      (super.noSuchMethod(Invocation.method(#put, [collectionName, key, value]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(String? collectionName, String? key) =>
      (super.noSuchMethod(Invocation.method(#delete, [collectionName, key]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  String toString() => super.toString();
}
