// Mocks generated by Mockito 5.0.15 from annotations
// in devnology/test/core/domain/usecases/list_all_product.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:devnology/core/domain/entities/product.dart' as _i2;
import 'package:devnology/core/domain/repositories/product_repository_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeProduct_0 extends _i1.Fake implements _i2.Product {}

/// A class which mocks [IProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProductRepository extends _i1.Mock
    implements _i3.IProductRepository {
  MockIProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Product>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i2.Product>>.value(<_i2.Product>[]))
          as _i4.Future<List<_i2.Product>>);
  @override
  _i4.Future<_i2.Product> get(String? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id]),
              returnValue: Future<_i2.Product>.value(_FakeProduct_0()))
          as _i4.Future<_i2.Product>);
  @override
  String toString() => super.toString();
}
